
try: 
    num2 = int(input("Digite um numero para comparacao : " ))
except:
    print ("Erro tipo de dado inserido")  

NUM1= 1 

if num2==NUM1:
    print('Números iguais')
else:
    print("Numeros diferentes")
    
num1 = int(input("Digite um numero para comparacao : " ))

NUM1= 1 

if num2==NUM1:
    print('Números iguais111')
else:
    print("Numeros diferentes2")
    
    # er4444 44 777 7
    
    
    import os
os.system('cls' if os.name == 'nt' else 'clear')

##se a média foi  >= 7 aprovado
#se a média for 4 , 6 recuperação
# senão reprovado 

if num2 == 1:  
    print('Os números são iguais.')
elif:
    print('Os números são iguais.')
else        
    print('Os números são iguais.')